sudo: required
arch:
  - amd64
dist: bionic
language: python
python:
 - "3.6"
env:
  global:
    - LD_LIBRARY_PATH=/usr/lib/llvm-6.0/lib
    - LLVM_HOME=/usr/lib/llvm-6.0
    - CC=clang-6.0
    - CXX=clang++-6.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-6.0
    packages:
      - clang-6.0
      - libclang-6.0
      - llvm-6.0
      - llvm-6.0-dev
install:
  - pip install .
script:
  - python setup.py test
